### ISSUE TITLE
Explore http4s entity handling

### ISSUE THREAD

**Issue by lindholc** [lasp/latis-hapi#15]
We need a better understanding of how `http4s` handles entities so we can stream LaTiS datasets.

**Comment by lindholc** [comment]
`http4s` represents response bodies as streams of bytes. We need an `EntityEncoder[F, A]` instance to turn `A` into said stream of bytes. (It also sets the appropriate values for `Content-Type`, `Content-Length`, and other headers.)

If `A` is already a stream, the response will be streamed.

If LaTiS writers produced iterators or streams of things, those things could be streamed in responses without much additional work.

Some links:
- [Entity handling](https://http4s.org/v0.18/entity/) (`http4s` docs)
- [`EntityEncoder.scala`](https://github.com/http4s/http4s/blob/release-0.18.x/core/src/main/scala/org/http4s/EntityEncoder.scala)

**Comment by dlindhol** [comment]
Sounds like there will be no show-stoppers. I suggest we start with the csv writer. We should be able to take a seq of LaTiS Samples and map a `Sample => String` function over it.
